import Box from '@mui/material/Box'
import Tooltip from '@mui/material/Tooltip'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import { colors, radius } from '@/theme/tokens'

interface AISummaryBadgeProps {
  /**
   * When false, renders nothing. Lets callers pass the raw
   * `score.notes_is_ai_summary` value without an outer conditional.
   */
  show?: boolean
}

const TOOLTIP_TEXT =
  'This note was generated by an AI summarizer from the underlying questionnaire narrative. Verify before signing off.'

/**
 * Small pill flagging a note as AI-generated. Token-styled rather than a
 * raw MUI Chip: the app theme sizes Chips for 28px+ list contexts, which
 * crushed the icon margins at this badge's scale, and the template "info"
 * palette read as off-brand translucent cyan. The pill is keyboard
 * focusable so the verify-before-signing-off tooltip is reachable without
 * a mouse.
 * @param {AISummaryBadgeProps} props - Show flag.
 * @returns {JSX.Element | null} The badge, or null when hidden.
 */
export default function AISummaryBadge({ show = true }: AISummaryBadgeProps) {
  if (!show) return null

  return (
    <Tooltip title={TOOLTIP_TEXT} arrow placement="top">
      <Box
        component="span"
        tabIndex={0}
        sx={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 0.5,
          px: 1,
          py: 0.25,
          borderRadius: `${radius.pill}px`,
          backgroundColor: colors.primary50,
          color: colors.ink900,
          fontSize: 11,
          fontWeight: 600,
          lineHeight: 1.4,
          whiteSpace: 'nowrap',
          cursor: 'default',
        }}
      >
        <AutoAwesomeIcon sx={{ fontSize: 12 }} aria-hidden="true" />
        AI Summary
      </Box>
    </Tooltip>
  )
}
