import { Chip, Tooltip } from '@mui/material'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'

interface AISummaryBadgeProps {
  /**
   * When false, renders nothing. Lets callers pass the raw
   * `score.notes_is_ai_summary` value without an outer conditional.
   */
  show?: boolean
}

const TOOLTIP_TEXT =
  'This note was generated by an AI summarizer from the underlying questionnaire narrative. Verify before signing off.'

export default function AISummaryBadge({ show = true }: AISummaryBadgeProps) {
  if (!show) return null

  return (
    <Tooltip title={TOOLTIP_TEXT} arrow placement="top">
      <Chip
        icon={<AutoAwesomeIcon sx={{ fontSize: '0.75rem !important' }} />}
        label="AI Summary"
        size="small"
        variant="outlined"
        color="info"
        sx={{ height: 18, fontSize: '0.65rem' }}
      />
    </Tooltip>
  )
}
