version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'America/New_York'
    ignore:
      - dependency-name: "node"
        versions: ["20.16.0"]
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    reviewers:
      - 'ATNoblis'
    versioning-strategy: increase