version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'America/New_York'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    reviewers:
      - 'ATNoblis'
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']