export const EMPTY_SYSTEM = {
  fismauid: '',
  fismaacronym: '',
  fismaname: '',
  fismasubsystem: '',
  fismaimpactlevel: '',
  mission: '',
  fismasystemid: 0,
  component: '',
  groupacronym: '',
  groupname: '',
  divisionname: '',
  datacenterenvironment: '',
  datacallcontact: '',
  issoemail: '',
  sdl_sync_enabled: false,
  decommissioned: false,
  decommissioned_date: null,
  decommissioned_by: null,
  decommissioned_notes: null,
}
