name: Analysis

on:
  workflow_call:

jobs:
  Snyk-Test:
    name: snyk test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Debug Snyk Token  
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "❌ SNYK_TOKEN is not available"
          else 
            echo "✅ SNYK_TOKEN is available (first 8 chars: ${SNYK_TOKEN:0:8}...)"
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high --show-vulnerable-paths=all ./

  Snyk-Code-Test:
    name: snyk code test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: code test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high --show-vulnerable-paths=all ./