name: Analysis

on:
  workflow_call:

jobs:
  Snyk-Test:
    name: snyk test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: test --severity-threshold=high --show-vulnerable-paths=all ./

  Snyk-Code-Test:
    name: snyk code test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Run Snyk Code test
        uses: snyk/actions/node@master
        with:
          args: code test --severity-threshold=high --show-vulnerable-paths=all ./