name: Orchestration PROD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:     
  ui:
    if: ${{ github.event.pull_request.merged }}
    name: ui
    uses: ./.github/workflows/ui.yml
    with:
      environment: prod
    secrets: inherit
  