name: Orchestration DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  ui:
    name: ui
    needs: 
      - analysis
    uses: ./.github/workflows/ui.yml
    with:
      environment: dev
    secrets: inherit
  