name: Orchestration PROD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  analysis:
    name: Analysis
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/analysis.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     
  ui:
    if: ${{ github.event.pull_request.merged }}
    name: ui
    needs: 
      - analysis
    uses: ./.github/workflows/ui.yml
    with:
      environment: prod
    secrets: inherit
  