/**
 * Barrel for the shared design-system components.
 * @module components/ds
 */
export { default as Modal } from './Modal'
export type { ModalProps, ModalSize } from './Modal'
export { default as DataGridPaginationFooter } from './DataGridPaginationFooter'
export type { DataGridPaginationFooterProps } from './DataGridPaginationFooter'
export { default as CompactSwitchLabel } from './CompactSwitchLabel'
export type { CompactSwitchLabelProps } from './CompactSwitchLabel'
export { default as ScoreDisplay } from './ScoreDisplay'
export type { ScoreDisplayProps } from './ScoreDisplay'
export { default as EmptyState } from './EmptyState'
export type { EmptyStateProps, EmptyStateTone } from './EmptyState'
export { default as IconActionButton } from './IconActionButton'
export type { IconActionButtonProps } from './IconActionButton'
export { default as PageHeader } from './PageHeader'
export type { PageHeaderProps } from './PageHeader'
export { default as StatusChip, CodeBadge } from './StatusChip'
export type { StatusChipProps, StatusKind, CodeBadgeProps } from './StatusChip'
export { default as Card } from './Card'
export type { CardProps } from './Card'
export { default as Eyebrow } from './Eyebrow'
export type { EyebrowProps } from './Eyebrow'
export { default as Stat } from './Stat'
export type { StatProps } from './Stat'
export { default as TierChip } from './TierChip'
export type { TierChipProps } from './TierChip'
export { default as TierLabel } from './TierLabel'
export type { TierLabelProps } from './TierLabel'
export { default as TrendLine } from './TrendLine'
export type { TrendLineProps } from './TrendLine'
export { default as CompactTrend } from './CompactTrend'
export type { CompactTrendProps } from './CompactTrend'
export { default as TrendingPill } from './TrendingPill'
export type { TrendingPillProps } from './TrendingPill'
